# Generated by Django 3.2.7 on 2022-05-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtransaction',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('void', 'Void'), ('delivered', 'Delivered'), ('force-delivered', 'Force Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('insufficient', 'Insufficient'), ('ticket-printed', 'Ticket-printed')], default='pending', max_length=15, null=True),
        ),
    ]
