# Generated by Django 3.2.3 on 2023-05-31 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0008_alter_vendorreviewrating_vendor'),
        ('transaction', '0002_alter_mealtransaction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodReviewQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('position', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('MULTIPLE_ANSWER', 'MULTIPLE_ANSWER'), ('SINGLE_ANSWER', 'SINGLE_ANSWER'), ('STAR_RATING', 'STAR_RATING')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_question', to='account.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='FoodReviewQuestionOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100, null=True)),
                ('required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_option', to='transaction.foodreviewquestion')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='FoodReviewResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_respsonse', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.foodreviewquestion')),
                ('selected_options', models.ManyToManyField(to='transaction.FoodReviewQuestionOption')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_rating', to='transaction.mealtransaction')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
