# Generated by Django 3.2.3 on 2023-06-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_foodreviewquestion_foodreviewquestionoption_foodreviewresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodreviewquestionoption',
            name='required',
        ),
    ]
