# Generated by Django 3.2.3 on 2023-06-15 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_remove_foodreviewquestionoption_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodreviewresponse',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='foodreviewresponse',
            name='selected_options',
        ),
        migrations.AddField(
            model_name='foodreviewresponse',
            name='selected_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_options', to='transaction.foodreviewquestionoption'),
        ),
    ]
