# Generated by Django 3.2.3 on 2023-06-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20230615_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreviewquestion',
            name='type',
            field=models.CharField(choices=[('SINGLE_ANSWER', 'SINGLE_ANSWER')], max_length=20),
        ),
    ]
