# Generated by Django 3.2.3 on 2023-06-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_alter_foodreviewquestion_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodreviewquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='foodreviewquestionoption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='foodreviewresponse',
            options={},
        ),
    ]
