# Generated by Django 3.2.3 on 2023-06-15 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20230615_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreviewresponse',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_question', to='transaction.foodreviewquestion'),
        ),
    ]
