# Generated by Django 3.2.3 on 2023-06-15 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_vendorreviewrating_vendor'),
        ('transaction', '0008_alter_foodreviewresponse_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreviewresponse',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_vendor', to='account.vendor'),
        ),
    ]
