# Generated by Django 3.2.3 on 2022-02-14 11:43

import account.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mirage.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('app_code', models.CharField(max_length=20, unique=True)),
                ('authorization_code', models.TextField(blank=True, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=100, null=True)),
                ('biometrics_a', models.TextField(blank=True, null=True)),
                ('biometrics_b', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[account.utils.validate_phone])),
                ('balance', models.FloatField(default=0)),
                ('actual_balance', models.FloatField(default=0)),
                ('pending_balance', models.FloatField(default=0)),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True)),
                ('is_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, max_length=50, null=True, upload_to='user')),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=7, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, max_length=50, null=True, upload_to='company')),
                ('sector', models.CharField(max_length=100)),
                ('app_key', models.CharField(max_length=20, unique=True)),
                ('ref_code', models.CharField(max_length=20, unique=True)),
                ('contact_first_name', models.CharField(max_length=20)),
                ('contact_last_name', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_phone_number', models.CharField(max_length=17, unique=True, validators=[account.utils.validate_phone])),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=10, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('authorization_code', models.TextField(blank=True, null=True)),
                ('transfer_recipient', models.CharField(blank=True, max_length=50, null=True)),
                ('balance', models.FloatField(default=0)),
                ('actual_balance', models.FloatField(default=0)),
                ('pending_balance', models.FloatField(default=0)),
                ('top_up_type', models.CharField(blank=True, choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpsid')], max_length=15, null=True)),
                ('use_card', models.BooleanField()),
                ('biometric_type', models.CharField(blank=True, choices=[('fingerprint', 'Fingerprint'), ('facial', 'Facial')], max_length=15, null=True)),
                ('use_biometric', models.BooleanField()),
                ('use_transaction_code', models.BooleanField()),
                ('allow_same_day_delivery', models.BooleanField()),
                ('allowed_booking_day', models.IntegerField()),
                ('notification_balance_limit', models.FloatField(blank=True, null=True)),
                ('is_comp_allow_txn_mix', models.BooleanField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('sid_transfer_recipient', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('service_fee', models.FloatField(blank=True, null=True)),
                ('sid_balance', models.FloatField(blank=True, default=0, null=True)),
                ('sid_pending_balance', models.FloatField(blank=True, default=0, null=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('cash_out_time', models.TimeField()),
                ('cancelling_grace_period_in_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('daily_limit', models.FloatField()),
                ('company_paid', models.FloatField()),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.company')),
            ],
            options={
                'unique_together': {('name', 'company')},
            },
        ),
        migrations.CreateModel(
            name='SIDAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('bank_code', models.CharField(blank=True, max_length=10, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('transfer_recipient', models.CharField(blank=True, max_length=20, null=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.company')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_keys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_key', mirage.fields.EncryptedTextField(blank=True, null=True)),
                ('private_key', mirage.fields.EncryptedTextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.company')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(max_length=250, unique='True')),
                ('device_id', models.TextField(blank=True, null=True, unique='True')),
                ('device_code', models.IntegerField(blank=True, null=True, unique='True')),
                ('is_active', models.BooleanField()),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.company')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.company')),
            ],
            options={
                'unique_together': {('name', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=250)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.company')),
            ],
            options={
                'unique_together': {('card_number', 'company')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='card_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.card'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.stafflevel'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussiness_name', models.CharField(max_length=50)),
                ('is_market_space', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_company', models.BooleanField()),
                ('bank_code', models.CharField(blank=True, max_length=10, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('transfer_recipient', models.CharField(blank=True, max_length=50, null=True)),
                ('cash_hold', models.BooleanField(blank=True, default=False, null=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_creator', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('bussiness_name', 'company')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'company')},
        ),
    ]
