# Generated by Django 3.2.7 on 2022-04-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_vendor_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_id',
            new_name='device_iid',
        ),
    ]
