# Generated by Django 3.2.7 on 2022-07-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_device_id_device_device_iid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_allow_any_day_ticket_scan',
            field=models.BooleanField(default=False),
        ),
    ]
