# Generated by Django 3.2.3 on 2023-03-09 15:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('transaction', '0002_alter_mealtransaction_status'),
        ('account', '0004_vendor_is_allow_any_day_ticket_scan'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_creator', to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_food', to='food.food')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='vendor_rating', to='transaction.mealtransaction')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='account.company')),
            ],
        ),
    ]
