# Generated by Django 3.2.3 on 2023-03-09 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_mealtransaction_status'),
        ('account', '0005_vendorreviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorreviewrating',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_rating', to='transaction.mealtransaction'),
        ),
    ]
