# Generated by Django 3.2.3 on 2023-03-09 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_vendorreviewrating_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorreviewrating',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='vendorreviewrating',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
    ]
