# Generated by Django 3.2.3 on 2023-03-09 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20230309_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorreviewrating',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='account.vendor'),
        ),
    ]
